language: python
notifications:
  email: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "easy_install -U setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - py.test tests/test_app.py --doctest-modules -v --cov app --cov-report term-missing
after_success:
  - coveralls